### ISSUE TITLE
Add support for Cucumber

### ISSUE THREAD

**Issue by fijijavis** [fijijavis/wdio-json-reporter#13]
Add support for Cucumber since it is a valid runner in the WDIO conf

**Comment by ania-s** [comment]
Is there any work planned on this? I am using this reporter now and it misses some cucumber data, like tags.

**Comment by fijijavis** [comment]
I have very limited experience with Cucumber.  If you’d like to take a crack at this and submit a PR I’d be happy to review & approve.

**Comment by fijijavis** [comment]
For now I'm going to call this done with PR #20 and #21
