### ISSUE TITLE
[Question] How to exclude tests from the reporting?

### ISSUE THREAD

**Issue by ianoroceo** [fijijavis/wdio-json-reporter#19]
Hi, it's more of a question than an issue. My apologies for my dumb question.
How can we exclude specific tests from the report?

the context on my question is we have a web application where the user workflow is login -> do something -> logout, and each test case revolves on that workflow. So to avoid adding the login and logout steps for each tests, I am adding the login and logout test beforeEach and afterEach tests

```
var login = require('../../AccountLogin/login.spec');
var logout = require('../../AccountLogin/logout.spec');

describe('The app', function() {
	beforeEach(function(login) {  
	});
    
	afterEach(function(logout) {
	});
	
	it('Login Test', function() {
		// assertions
	});
  
});
```

my dilemma now is, on the json reporter, it is showing 3 passed test cases

```
[chrome #0-0] Session ID: 7c4173de6e2aa069bfa28a7e81993416
[chrome #0-0] Spec: C:\Users\iano\Repos\Automation\Web\specs\Portal\smokeTests\app.spec.js
[chrome #0-0] Running: chrome
[chrome #0-0]
[chrome #0-0] QA_Login
[chrome #0-0]   √ Login
[chrome #0-0]
[chrome #0-0] QA_Logout
[chrome #0-0]   √ Logout
[chrome #0-0]
[chrome #0-0] QA_Smoke Tests for App
[chrome #0-0]   √ C663811 Login with Valid Credentials/C663832 Multi-Portal User Selects Active Portal
[chrome #0-0]
[chrome #0-0]
[chrome #0-0] 3 passing (38s)
[chrome #0-0]

Wrote json report to [./Reports].


3 passing (40.90s)
```

so each spec file will show 3 passed. and some of my spec files, I have 2-3 tests, so it will show 6 or 9 pass test cases if its executed.

**Comment by ianoroceo** [comment]
i'm closing this issue.. nevermind my question.
the re-usable parts of the login and login, I moved it to  page objects and add it as method.. my bad guys

**Comment by fijijavis** [comment]
@ianoroceo Glad you were able to figure out a solution.
