### ISSUE TITLE
testSuite.name should be original

### ISSUE THREAD

**Issue by monolithed** [fijijavis/wdio-json-reporter#2]
```js
describe('TEST-1', () => { // `TEST-1` is an issue number in JIRA.
    it('Test 1', () => { });
});
```

```js
{
	"suites": [
		{
			"name": "test_2" 
		}
	]
}
```

https://github.com/fijijavis/wdio-json-reporter/blob/master/lib/reporter.js#L57

Could you fix it?

**Comment by fijijavis** [comment]
To make sure we are on the same page, the hyphen in the suite name is causing an issue?

**Comment by monolithed** [comment]
Yep, hyphen and lowercase are both. What is the original purpose of that?

**Comment by fijijavis** [comment]
Sorry for the delayed response.  Forgot about this over the weekend.  

That was a straight copy from the JUNIT version so I'm not sure what that was for.  I'll fix it and get out a new version today.

**Comment by monolithed** [comment]
I got it, thanks!

**Comment by fijijavis** [comment]
v 0.0.3 is now available
