### ISSUE TITLE
Report creation with '|' in name fails

### ISSUE THREAD

**Issue by dgasi** [fijijavis/wdio-json-reporter#3]
Hi,
I noticed when using wdio-json-reporter if you have large number of files that it fails after 28 files:
.
.
.
Wrote json report to [reports].
Wrote json report to [reports].
Failed to write json report to [reports]. Error: Error: ENOENT: no such file or directory, open '%PATH%\WDIO.json.chrome.0|.json'

So reports CID it starts with '0a' and after going trough the alphabet it starts with special characters because it created: WDIO.json.chrome.0}.json and then tried WDIO.json.chrome.0|.json where it failed.

So is it possible to reformat the name or to use numbers instead of characters?

Thx.

**Comment by fijijavis** [comment]
Sure.  I'll take a look at this later today.

**Comment by dgasi** [comment]
Hi,

Any news regarding this issue?

Thx.

**Comment by fijijavis** [comment]
Sorry... Got had some things come up between work and home.  Will look at this today.

**Comment by fijijavis** [comment]
By any chance have you tried using the [wdio-junit-reporter](https://github.com/webdriverio/wdio-junit-reporter)?  I'm curious to see if the problem exists there too.  

CID is generated from within WDIO so I'm thinking it might make more sense to address this issue at the root instead of a one off fix here.

@christian-broman Could you take a look and give your thoughts?

**Comment by dgasi** [comment]
Just checked with Junit reporter and it's the same thing.

**Comment by dgasi** [comment]
@fijijavis - I opened the issue on webdriverio project and got response from @christian-bromann:

> @dgasi I think we should not include the capability id in the name then. I think this should be fixed in the json reporter then.

does this help you to fix the issue?

**Comment by fijijavis** [comment]
Yes, I guess that does.  If the direction is to not use cid in the name of the file then I'll work on an adjustment.

**Comment by dgasi** [comment]
thanks man. let me know when you have it done I can try it out really fast.

**Comment by fijijavis** [comment]
Published v0.0.4 with the above referenced change.  I tried it with a 2 spec files and it looks good.  Let me know what you think

**Comment by dgasi** [comment]
Hi,

Just did a run and no fails in reports creation .Works like a charm :-D

Thanks man.
