### ISSUE TITLE
Merge results - function arguments as input parameters

### ISSUE THREAD

**Issue by kmnaid** [fijijavis/wdio-json-reporter#30]
The function mergeResults takes arguments as input which are not used by it.
It uses the process arguments - `process.argv[2] and process.argv[3]` to set the directory and file pattern. 
This function is called from other scripts that could have different process arguments set and hence does not work for this case. Can mergeResults instead use the arguments sent to it to get the directory and file pattern?

**Comment by kmnaid** [comment]
@fijijavis : Do you think this could be changed?

**Comment by fijijavis** [comment]
@kmnaid yes.  I thought there was an open PR but I can’t find it now???

**Comment by kmnaid** [comment]
@fijijavis : Oh I see, I can create one.

**Comment by fijijavis** [comment]
PR #42 resolves the issue
