### ISSUE TITLE
Feature Request: Include 'state' of hook in result

### ISSUE THREAD

**Issue by kmnaid** [fijijavis/wdio-json-reporter#31]
**Describe the solution you'd like**
Include the state of a hook in results so while reading the results it is similar to reading the state of a test

**Describe alternatives you've considered**
To get the state of a hook, check if there are errors in the hook object.

```
"hooks": [
        {
          "start": "2019-07-12T02:53:02.029Z",
          "end": "2019-07-12T02:53:02.036Z",
          "duration": 7,
          "title": "\"before all\" hook",
          "associatedSuite": "webdriver.io page",
          "errorType": "AssertionError",
          "error": "expected 1 to equal 6",
          "standardError": "AssertionError: expected 1 to equal 6\n    at Context.equal (example/test/basicTest.js:4:16)"
        }
      ]
```

**Comment by kmnaid** [comment]
Fixed by the merged [PR](https://github.com/fijijavis/wdio-json-reporter/pull/32).

**Comment by fijijavis** [comment]
@kmnaid What test runner are you using?  #34 was raised and appears to show an issue with this change when using Mocha.  So I'm curious if you are using Mocha or maybe Jasmine.

**Comment by kmnaid** [comment]
@fijijavis: I am using Mocha.
