### ISSUE TITLE
sopport for wdio vs 6

### ISSUE THREAD

**Issue by pmerwin** [fijijavis/wdio-json-reporter#45]
Can we create a new version to support vs 6?

"peerDependencies": {
    "@wdio/cli": "^6.0.15"
  },

https://github.com/fijijavis/wdio-json-reporter/pull/46

**Comment by fijijavis** [comment]
@pmerwin I'll check this out tonight (US Eastern) and get a new version published.  Thanks!

**Comment by pmerwin** [comment]
Rad thanks Jim!!!

**Comment by fijijavis** [comment]
@pmerwin published version 2.0.0

**Comment by pmerwin** [comment]
Thanks again!
