### ISSUE TITLE
Move project to WebdriverIO Community Org

### ISSUE THREAD

**Issue by christian-bromann** [fijijavis/wdio-json-reporter#63]
Hey @fijijavis ,

first off, thank you for creating this plugin and extending the WebdriverIO ecosystem!

We have been looking into successful WDIO plugins like this one as we want to ensure that its development can be continued even if the original maintainer decides to move on. Therefore on behalf of the WebdriverIO community I would like to ask if you would be interested to move this repository into the [WebdriverIO Community](https://github.com/webdriverio-community) organisation. It would allow us to help maintain this package, automate a few things like releases and allow others to contribute to it and make the package even better. You would of course continue to have full access to it.

What do you think? Please let me know if you have any questions.

**Comment by vdrulerz** [comment]
@fijijavis Hi...can you please consider above request from Christian sooner rather than later, currently a lot of things are breaking while using this reporter when the framework is 'cucumber'...refer to below screenshot

![image](https://user-images.githubusercontent.com/6131428/127142440-01bd7f7a-a0f7-4c07-bfb7-b4e6508b9976.png)

I understand you are no longer using WebdriverIO but making it up and running and get it compatible with latest webdriverIO will be really helpful

Thanks !

**Comment by christian-bromann** [comment]
ping @fijijavis

**Comment by fijijavis** [comment]
@christian-bromann Sorry for missing the notifications.  Yeah I think it is fine for this to move.

**Comment by christian-bromann** [comment]
Awesome, I just invited you to the org. Here are the two things you would need to do:

- transfer the repository to the `webdriverio-community` GitHub organisation (see docs [here](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository))
- add [`wdio-user`](https://www.npmjs.com/~wdio-user) as NPM maintainer to the package (see docs [here](https://docs.npmjs.com/cli/v7/commands/npm-adduser))

Again, thank you so much for all the work and I hope, to keep you as a maintainer in the WebdriverIO ecosystem. You continue to have access and release access to this repository at all times.

**Comment by wyhmichael** [comment]
@fijijavis @christian-bromann any updates on this move?

**Comment by christian-bromann** [comment]
@fijijavis can we transfer this project over?

**Comment by PetrKnedlik** [comment]
ping @fijijavis

**Comment by PavanMudigonda** [comment]
ping @fijijavis

**Comment by PavanMudigonda** [comment]
It seems we are pinging @fijijavis  from last two years.

@christian-bromann  Is there any workaround like cloning this repo under WDIO community ?

**Comment by christian-bromann** [comment]
We could just clone the code base and move it to `@wdio/json-reporter` but I would be more interested having @fijijavis on board with this.

**Comment by PavanMudigonda** [comment]
I can see @fijijavis is active on GitHub. 

@fijijavis Jim could you please provide confirmation to @christian-bromann

**Comment by PetrKnedlik** [comment]
@fijijavis 🙏please get in touch with us

Maybe @christian-bromann can you sent him an email or something? :) On Twitter he seems not that active anymore.

**Comment by JiangHongTiao** [comment]
Hi guys, can we do something with this? I'm creating a new project and I do not want to go with old dependencies, however I would be happy to use this reporter. It will simplify things for us. Thanks 🙏

**Comment by christian-bromann** [comment]
Since this project doesn't seem to be maintained anymore, we have taken the source and added it to the WebdriverIO core project. You can now use it with WebdriverIO v8 by replacing the package from `wdio-json-reporter` to `@wdio/json-reporter`. The rest should work the same way. Let me know if you encounter any issues and feel free to raise issues around this reporter in the [main repository](https://github.com/webdriverio/webdriverio) moving forward.
