### ISSUE TITLE
npm audit - Vulnerabilities Observed in dependent package 

### ISSUE THREAD

**Issue by deepakb2410** [fijijavis/wdio-json-reporter#64]
───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Regular expression denial of service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ glob-parent                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=5.1.2                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ wdio-json-reporter [dev]                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ wdio-json-reporter > jest-matchers > jest-message-util >     │
│               │ micromatch > parse-glob > glob-base > glob-parent            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1751                            │
└───────────────┴──────────────────────────────────────────────────────────────┘

**Comment by wyhmichael** [comment]
Will be addressed once https://github.com/fijijavis/wdio-json-reporter/pull/69 merged
